const SALT_ROUNDS = 10;
const PAGE_SIZE = 4;
const FILTER_TRUE = 1;
const DEFAULT_PASSWORD = '123';
const DEFAULT_CLASS = 4

module.exports = { SALT_ROUNDS, PAGE_SIZE, FILTER_TRUE, DEFAULT_PASSWORD, DEFAULT_CLASS };
